@rootAPI = http://localhost:8200/api/v1/store


### post user
POST {{rootAPI}}/user 
Content-Type: application/json

{
    "fName":"kiran",
    "lName":"manandhar",
    "phone":"1555555",
    "password":"dkkdkdd",
"email":"kiranmanandhar956@gmail.com",
"address":"dkdkdk"
}

### post user
GET  {{rootAPI}}/user/login
Content-Type: application/json



### post user
GET  {{rootAPI}}/user/get-users
Content-Type: application/json




### get all categories
GET {{rootAPI}}/catagory



### get all the product

GET {{rootAPI}}/product/category/64cf22746d42008d63a59392

### get all the payment Options

GET {{rootAPI}}/payment/



### 
POST {{rootAPI}}/

