@rootAPI = http://localhost:8200/api/v1/store

### get all categories
GET {{rootAPI}}/catagory



### get all the product

GET {{rootAPI}}/product/category/64cf22746d42008d63a59392

### get all the payment Options

GET {{rootAPI}}/payment/
